#!/bin/bash

# Janusz Ładecki <szunaj13pl@gmail.com>
# 21.09.2017

# echo $i

function measureScreen(){
    rows=$(tput lines)
    cols=$(tput cols)
}

function createGui(){
    
    
    local TYPE="menu"
    local HEIGHT=$((rows - 3))
    local WIDTH=$(( cols / 2))
    local CHOICE_HEIGHT=$(( rows - 5))
    local MENU="by Janusz Ładecki\n\nChoose repo to clone:"
    
    local OPTIONS=($(cat --number --squeeze-blank --number-nonblank data))
    
    # local CHOICES=$(dialog --menu \
    #     "MENU" \
    #     300 300 200 \
    # "${OPTIONS[@]}" 2>&1 >/dev/tty)
    
    local CHOICES=$( dialog --menu \
        "MENU" \
        300 300 200 \
    "${OPTIONS[@]}" 2>&1 >/dev/tty)
    
    
    # $HEIGHT $WIDTH $CHOICE_HEIGHT \
    # clear
    
    # echo $CHOICESa
    # for choice in \$CHOICES
    # do
    #     case \$choice in
    
    # esac
    # done
    # dialog --title "Equinoxes and Solistices"  \
    # --radiolist "When is the Winter Solictice?" 15 60 4 \
    # "${OPTIONS[@]}" \
    # 2>&1 >/dev/tty
}

measureScreen
createGui
#  Symfony
#  true
#  git chown sudo_chown composer_install

#  PHP aplications
#  false
#  git chown sudo_chown composer_install

#  Angular aplications
#  false
#  git chown sudo_chown npm_install


